### PR TITLE
Assignment 2

### PR DESCRIPTION
**Pull request by MRKGITCODE**
## Checklist
- [ ] I can confirm that my changes are working as intended

### CODE REVIEW

**Comment by MRKGITCODE** [comment]
updated

**Comment by MRKGITCODE** [comment]
updated

**Comment by MRKGITCODE** [comment]
updated

**Review by KasraVakiloroayaei — COMMENTED** [review]
A2: Complete 

You need to submit your Pull request under the correct branch. Please follow the instructions given to you. This is the case for all three of your assignments, thus making it difficult to find and provide feedback

**Pull request merged**
